### ISSUE TITLE
Need test data

### ISSUE THREAD

**Issue by christianbundy** [TerraSeer/windshaft-terraseer#8]
I've got everything working perfectly with Elastic Beanstalk at http://steven-tiler-test.elasticbeanstalk.com/, but I don't have any data. @enam do we have a dataset that I can import that's smaller than the database used in production?

**Comment by enam** [comment]
Sweet! Sorry to be so slow! Do you just want a single geospatial table? You could pull out the county_2010 table, should be a good one to use. Do you want me to make a dump file?

**Comment by enam** [comment]
@christianbundy here is a link for the sql dump for county_2010
https://app.box.com/s/to3tm8wohb8ox71n3vcjlb8vqgtfmwnj

**Comment by christianbundy** [comment]
Do you know which version of PostgreSQL the dump came from? It's not playing nicely with the database I have and I'm trying to work through the possibilities.

**Comment by enam** [comment]
Was from my local PostgreSQL, says 9.3.5

**Comment by enam** [comment]
Version info should be in the file, is it throwing any readable errors?  Should look something like...

``` sql
--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.5
-- Dumped by pg_dump version 9.3.1
```

**Comment by christianbundy** [comment]
@enam Oops, yeah I totally didn't look at that. Here's the first error I get before it quits:

``` console
[user@host] $ psql -U postgres < county_2010.sql
SET
SET
SET
SET
SET
SET
SET
SET
SET
ALTER TABLE
ERROR:  invalid input syntax for integer: ""
CONTEXT:  COPY county_2010, line 3222, column ogc_fid: ""
```

**Comment by enam** [comment]
That is the end of the file. hmm.

**Comment by enam** [comment]
OK, truncated it to make it a bit more manageable. See if this will work for you. https://app.box.com/s/uppzhn1ny3xf1wq4hpsx6zflroxkhmec

**Comment by enam** [comment]
Still has the create table in it, which you probably don't need. In fact, you may have a full table already, since the error was at the end of the import!

**Comment by christianbundy** [comment]
:raised_hands: http://steven-tiler-test.elasticbeanstalk.com/database/postgres/table/county_2010/0/0/0.png
